export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const IS_LOGGIN_IN = 'IS_LOGGIN_IN';
export const SIGNUP_EMAIL = 'SIGNUP_EMAIL';
export const USER_MESSAGE = 'USER_MESSAGE';
export const DISMISS_USER_MESSAGE = 'DISMISS_USER_MESSAGE';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const ON_NEW_PRODUCT_ADD_START = 'ON_NEW_PRODUCT_ADD_START';
export const ADD_PRODUCT_INPUT_CHANGE = 'ADD_PRODUCT_INPUT_CHANGE';
export const PRODUCT_REQUEST_START = 'PRODUCT_REQUEST_START';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const PRODUCT_REQUEST_FAIL = 'PRODUCT_REQUEST_FAIL';
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
export const REQUESTED_PRODUCT_LOADED = 'REQUESTED_PRODUCT_LOADED';

export const GET_PRODUCTS_BY_CATEGORY = 'GET_PRODUCTS_BY_CATEGORY';
